#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 01 13:54:08 UTC 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim count6_tb_behav -key {Behavioral:sim_1:Functional:count6_tb} -tclbatch count6_tb.tcl -log simulate.log"
xsim count6_tb_behav -key {Behavioral:sim_1:Functional:count6_tb} -tclbatch count6_tb.tcl -log simulate.log

